### ISSUE TITLE
위젯 명령어 —skip 옵션 추가

### ISSUE THREAD

**Issue by wlghdu97** [xpressengine/xe_cli#14]
—skip 옵션이란 user confirm없이 컴포넌트를 바로 만들 수 있는 옵션

이전에 스킨 명령어들에 추가한 것과 같이, 위젯 커맨드들에도 필요합니다.

**Comment by xharpenParksuhyeon** [comment]
위젯의 경우 아래와 같은 프로세스로 작동하고 있습니다.

위젯 생성 확인 -> 위젯 생성 -> (생성한 위젯에 대한 스킨 만들지 확인 -> 스킨 생성) * 사용자가 원하는 만큼

처음 위젯 생성에 대한 코멘드를 실행할 땐 위젯에 대한 정보만 받고 있습니다.
그후 추가적인 입력을 통해 생성할 스킨의 수 만큼 정보를 받아주고 있습니다.  

그렇기 때문에 --skip 옵션이 설정된 경우엔 --skip-skin-name 으로 입력받은 값을 통해 해당하는 위젯을 만들어주게 변경합니다.
